### ISSUE TITLE
Code availability?

### ISSUE THREAD

**Issue by kobeho24** [czbiohub/tabula-muris-senis#1]
Just wonder if the code for analysis would be available any time soon. I downloaded the processed data of droplet scRNA-seq in h5ad. Need some info about how the raw data was processed to do some downstream analysis.

Cheers,
Gary

**Comment by NMinato77** [comment]
I am also working on the processed data, and need more information to analyze them properly.
For example, why are there no mitochondrial genes in the count matrix? 
Why are the numbers of cell types in the data different from those on the interactive web page?
Could you give us more details about how the data were processed?

Best,
Minato

**Comment by aopisco** [comment]
@NMinato77 thank you for the reminder. The reference genome we used did not contain mitochondrial genes but I'm working on making those available. The interactive browser is currently being updated with the objects you can find here: https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis/Data-objects/?region=us-west-2
As for the processing the revised manuscript (https://www.biorxiv.org/content/10.1101/661728v2) contains a diagram in EDFig2 with the steps and the code will be made available shortly.

**Comment by NMinato77** [comment]
@aopisco 
Thank you very much for your quick reply; this is very helpful.
I continue to work on and make the most of your precious data, and look forward to the update.

Best,
Minato

**Comment by NMinato77** [comment]
@aopisco 
I have tried the following two objects on AWS:
tabula-muris-senis-droplet-raw-official-annotations.h5ad
tabula_sc/tabula-muris-senis-droplet-raw-official-annotations.h5ad

However, I've got AttributeError like below on both of them.
Are they broken?

```
raw_data = sc.read_h5ad("tabula-muris-senis-droplet-raw-official-annotations.h5ad")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dice1988/anaconda3/envs/mt/lib/python3.7/site-packages/anndata/readwrite/read.py", line 447, in read_h5ad
    constructor_args = _read_args_from_h5ad(filename=filename, chunk_size=chunk_size)
  File "/home/dice1988/anaconda3/envs/mt/lib/python3.7/site-packages/anndata/readwrite/read.py", line 502, in _read_args_from_h5ad
    return AnnData._args_from_dict(d)
  File "/home/dice1988/anaconda3/envs/mt/lib/python3.7/site-packages/anndata/core/anndata.py", line 2157, in _args_from_dict
    if key in d_true_keys[true_key].dtype.names:

AttributeError: 'dict' object has no attribute 'dtype'
```

Best,
Minato

**Comment by aopisco** [comment]
@NMinato77 I've just updated the objects in there. Can you please try again? Sorry for this!

**Comment by NMinato77** [comment]
@aopisco 
Are they public? I cannot download them.
It says
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>D7B31D75CD0671FB</RequestId>
<HostId>
/xCMV15Rp1L/seABHNi9mEOvQdt9wJ82uum0KnO61Nc/IWqQN/sVwyjHckRLr4Dpbm8pAu8TVgA=
</HostId>
</Error>
```


and the access is denied.

**Comment by aopisco** [comment]
I made the whole folder public again - please let me know if you still have problems.

**Comment by NMinato77** [comment]
@aopisco 
Finally, they work; I successfully downloaded them and loaded them.
Thank you very much for your kind and quick help.

**Comment by aopisco** [comment]
@kobeho24 let me know if the jupyter notebooks now available are easy to read and work with
